# cloudbuild.yaml — build & deploy from source (no pack image)
substitutions:
  _SERVICE_NAME: line-gatekeeper
  _REGION: asia-southeast1

steps:
  # Make sure the Artifact Registry repo exists (idempotent)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Setup-Artifact-Registry
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        REPO=cloud-run-source-deploy
        REGION=${_REGION}
        if ! gcloud artifacts repositories describe "$REPO" \
              --location "$REGION" --format="value(name)"; then
          gcloud artifacts repositories create "$REPO" \
            --repository-format=docker \
            --location "$REGION"
        fi

  # Build + deploy using Cloud Run "source deploy" (uses Google Buildpacks)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy-From-Source
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        gcloud run deploy ${_SERVICE_NAME} \
          --source . \
          --region ${_REGION} \
          --allow-unauthenticated \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY
